services:
  server:
    build: .
    container_name: cut_server
    user: 1000:1000
    volumes:
      - .:/app
    ports:
      - 8000:8000
    links:
      - database

  database:
    image: mysql:latest
    container_name: cut_database
    ports:
      - 3306:3306
    env_file:
      - .env.mysql