<script lang="ts">
import Card from '../components/Card.svelte';
import Feature from '../components/Feature.svelte';
import QrCode from "../../static/qr-code.svg"
import PasswordProtected from "../../static/password-protected.svg"
import NoPersonalData from "../../static/personal-data.svg"
import Accordion from '../components/Accordion.svelte';
import Eye from '../icons/Eye.svelte';
import EyeSlash from '../icons/EyeSlash.svelte';
import { slide } from 'svelte/transition';
import { push } from 'svelte-spa-router';
import { isProtected, originalUrl, shortenedUrl } from '../Store';

interface FeatureItem {
	title: string;
	image: string;
	text: string
}

let protect = false
let showPassword = false

const togglePasswordShow = () => {
	showPassword = !showPassword
}

const shortenUrl = () => {
	shortenedUrl.set("https://cut.dev.br/QxSDE2")
	originalUrl.set("https://test.com.br/How-To-Encrypt-Data")
	isProtected.set(protect)
	push('/result')
}

const features: FeatureItem[] = [{
	title: "Shorten, Scan and go!",
	text: "Every shortened URL generate a corresponding QR Code",
	image: QrCode
}, {
	title: "Password Protection",
	text: "Encrypt shortened URLs and protect them with a password",
	image: PasswordProtected
}, {
	title: "No tracking data",
	text: "No data is collected! Stay free of UTMs and tracking tags*",
	image: NoPersonalData
}]

</script>
<div class="w-full h-full flex justify-center items-center flex-col">
	<Card class="w-3/5">
		<h1 class="font-black font-akshar text-bright-gray-500 text-4xl py-2 px-8 text-center">Enter a URL and start shortening!</h1>
		<div class="flex w-full items-center px-2 pb-2">
			<input class="w-full bottom-0 top-0 h-10 border-pelorous-300 border-2 border-r-0 rounded-l-md" type="url" />
			<button on:click={shortenUrl} class="uppercase hover:bg-pelorous-600 bg-pelorous-300 text-white font-bold px-4 py-2 h-10 rounded-r-md">Short</button>
		</div>
		<Accordion class="w-1/3 ml-2">
			<h2 slot="title" class="font-bold mr-2">Options</h2>
			<label><input type="checkbox" bind:checked={protect}/> Enable password protection</label>

			{#if protect}
				<div transition:slide class="rounded-md border-2 border-pelorous-300 w-fit flex items-center">
					<input class="rounded-l-md" type={showPassword ? 'text' : 'password'}>
					<button class="w-fit mx-1" on:click={togglePasswordShow}>
						{#if showPassword}
							<Eye />
						{:else}
							<EyeSlash />
						{/if}
					</button>
				</div>
			{/if}
		</Accordion>
	</Card>
	<Card class="w-3/5 mt-4 py-8">
		<div class="grid grid-cols-3 gap-10 px-2">
			{#each features as feature}
				<Feature title={feature.title} image={feature.image} text={feature.text} />
			{/each}
		</div>
	</Card>
	<div class="w-3/5 mt-2">
		<p class="text-xs text-left">* UTMs present in the original URL are preserved. No new tracking tag is generated by CUT</p>
	</div>
</div>