<script>
    import Card from '../components/Card.svelte';
</script>
<div class="w-full h-full flex justify-center items-center flex-col flex-1 my-20">
    <Card class="w-4/5 md:w-3/5">
        <h1 class="text-center font-black font-akshar text-bright-gray-500 text-4xl py-2">Privacy Policy</h1>
        <p>Last updated: June 18, 2024</p>
        <p>This Privacy Policy describes Our policies and procedures on the collection, use and disclosure of Your
            information when You use the Service and tells You about Your privacy rights and how the law protects
            You.</p>
        <h2 class="text-left font-black font-akshar text-bright-gray-500 text-3xl py-2">Interpretation and Definitions</h2>
        <h3 class="text-left font-black font-akshar text-bright-gray-500 text-2xl py-2">Interpretation</h3>
        <p>The words of which the initial letter is capitalized have meanings defined under the following conditions.
            The following definitions shall have the same meaning regardless of whether they appear in singular or in
            plural.</p>
        <h3 class="text-left font-black font-akshar text-bright-gray-500 text-2xl py-2">Definitions</h3>
        <p>For the purposes of this Privacy Policy:</p>
        <ul class="flex flex-col ml-6 list-disc">
            <li>
                <p><strong>Application</strong> refers to CUT, the software program provided by the Company.</p>
            </li>
            <li>
                <p><strong>Company</strong> (referred to as either &quot;the Company&quot;, &quot;We&quot;, &quot;Us&quot;
                    or &quot;Our&quot; in this Agreement) refers to CUT.</p>
            </li>
            <li>
                <p><strong>Country</strong> refers to: Brazil</p>
            </li>
            <li>
                <p><strong>Device</strong> means any device that can access the Service such as a computer, a cellphone
                    or a digital tablet.</p>
            </li>
            <li>
                <p><strong>Personal Data</strong> is any information that relates to an identified or identifiable
                    individual.</p>
            </li>
            <li>
                <p><strong>Service</strong> refers to the Application.</p>
            </li>
            <li>
                <p><strong>Service Provider</strong> means any natural or legal person who processes the data on behalf
                    of the Company. It refers to third-party companies or individuals employed by the Company to
                    facilitate the Service, to provide the Service on behalf of the Company, to perform services related
                    to the Service or to assist the Company in analyzing how the Service is used.</p>
            </li>
            <li>
                <p><strong>Usage Data</strong> refers to data collected automatically, either generated by the use of
                    the Service or from the Service infrastructure itself (for example, the duration of a page visit).
                </p>
            </li>
            <li>
                <p><strong>You</strong> means the individual accessing or using the Service, or the company, or other
                    legal entity on behalf of which such individual is accessing or using the Service, as applicable.
                </p>
            </li>
        </ul>
        <h2 class="text-left font-black font-akshar text-bright-gray-500 text-3xl py-2">Collecting and Using Your Personal Data</h2>
        <h3 class="text-left font-black font-akshar text-bright-gray-500 text-2xl py-2">Types of Data Collected</h3>
        <h4>Personal Data</h4>
        <p>We don't collect any Name, Email. Phone number, Country, ID or any other personal data that can connect you to any shortened URL</p>
        <ul>
            <li>Usage Data</li>
        </ul>
        <ul>
           <li>We do not sell or share any information with third parties, except as necessary to provide our services or as required by law.</li>
        </ul>
        <h3 class="text-left font-black font-akshar text-bright-gray-500 text-2xl py-2">Security of Your Personal Data</h3>
        <p>The security of Your Personal Data is important to Us, but remember that no method of transmission over the
            Internet, or method of electronic storage is 100% secure. While We strive to use commercially acceptable
            means to protect Your Personal Data, We cannot guarantee its absolute security.</p>
        <h2 class="text-left font-black font-akshar text-bright-gray-500 text-3xl py-2">Links to Other Websites</h2>
        <p>The destination of shortened URLs to other websites are not operated by Us. If You click on a third party
            link, You will be directed to that third party's site. We strongly advise You to review the Privacy Policy
            of every site You visit.</p>
        <p>We have no control over and assume no responsibility for the content, privacy policies or practices of any
            third party sites or services.</p>
        <h2 class="text-left font-black font-akshar text-bright-gray-500 text-3xl py-2">Changes to this Privacy Policy</h2>
        <p>We may update Our Privacy Policy from time to time. We will notify You of any changes by posting the new
            Privacy Policy on this page.</p>
        <p>We will let You know via email and/or a prominent notice on Our Service, prior to the change becoming
            effective and update the &quot;Last updated&quot; date at the top of this Privacy Policy.</p>
        <p>You are advised to review this Privacy Policy periodically for any changes. Changes to this Privacy Policy
            are effective when they are posted on this page.</p>
        <h2 class="text-left font-black font-akshar text-bright-gray-500 text-3xl py-2">Contact Us</h2>
        <p>If you have any questions about this Privacy Policy, You can contact us:</p>
        <ul>
            <li>By email: support@cut.dev.br</li>
        </ul>
    </Card>
</div>
